# Generated by Django 5.0.7 on 2024-08-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labmanagement', '0003_patientreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
