# Generated by Django 5.0.7 on 2024-08-27 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labmanagement', '0004_pendingrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_content', models.TextField()),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('lab_test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='labmanagement.labtest')),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('date_verified', models.DateTimeField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labmanagement.labreport')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabResultVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField()),
                ('lab_test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='labmanagement.labtest')),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabTestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(choices=[('HB', 'HB'), ('WBC', 'WBC'), ('PLT', 'PLT'), ('RBC', 'RBC'), ('BF', 'BF'), ('WIDAL', 'WIDAL'), ('BLOOD GROUP', 'BLOOD GROUP'), ('URINE R/E', 'URINE R/E'), ('STOOL R/E', 'STOOL R/E'), ('HIV', 'HIV'), ('VDRL', 'VDRL'), ('SICKLING TEST', 'SICKLING TEST'), ('LFT', 'LFT'), ('RFT', 'RFT'), ('FBS/RBS', 'FBS/RBS'), ('HBsAg', 'HBsAg')], max_length=50)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('VERIFIED', 'Verified')], default='PENDING', max_length=20)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='labreport',
            name='test_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labmanagement.labtestrequest'),
        ),
    ]
