# Generated by Django 5.0.7 on 2024-09-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labmanagement', '0006_labtestrequest_patient_name_labtestrequest_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtestrequest',
            name='test',
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='custom_test_name',
            field=models.CharField(blank=True, help_text='If the test name is not in the predefined choices, add it here.', max_length=255),
        ),
        migrations.AlterField(
            model_name='labtestrequest',
            name='test_name',
            field=models.CharField(blank=True, choices=[('HB', 'HB'), ('WBC', 'WBC'), ('PLT', 'PLT'), ('RBC', 'RBC'), ('BF', 'BF'), ('WIDAL', 'WIDAL'), ('BLOOD GROUP', 'BLOOD GROUP'), ('URINE R/E', 'URINE R/E'), ('STOOL R/E', 'STOOL R/E'), ('HIV', 'HIV'), ('VDRL', 'VDRL'), ('SICKLING TEST', 'SICKLING TEST'), ('LFT', 'LFT'), ('RFT', 'RFT'), ('FBS/RBS', 'FBS/RBS'), ('HBsAg', 'HBsAg')], default='', max_length=50),
        ),
    ]
