# Generated by Django 5.0.7 on 2024-09-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labmanagement', '0007_remove_labtestrequest_test_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labresult',
            name='report',
        ),
        migrations.RemoveField(
            model_name='labresult',
            name='verified_by',
        ),
        migrations.DeleteModel(
            name='PatientReport',
        ),
        migrations.DeleteModel(
            name='PendingRequest',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='maintenance_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='labtestrequest',
            name='custom_test_name',
            field=models.CharField(blank=True, help_text='Enter a custom test name if needed.', max_length=255),
        ),
        migrations.AlterField(
            model_name='labtestrequest',
            name='patient_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='labtestrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Verified', 'Verified')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='labtestrequest',
            name='test_name',
            field=models.CharField(blank=True, choices=[('HB', 'HB'), ('WBC', 'WBC'), ('PLT', 'PLT'), ('RBC', 'RBC'), ('BF', 'BF'), ('WIDAL', 'WIDAL'), ('BLOOD GROUP', 'BLOOD GROUP'), ('URINE R/E', 'URINE R/E'), ('STOOL R/E', 'STOOL R/E'), ('HIV', 'HIV'), ('VDRL', 'VDRL'), ('SICKLING TEST', 'SICKLING TEST'), ('LFT', 'LFT'), ('RFT', 'RFT'), ('FBS/RBS', 'FBS/RBS'), ('HBsAg', 'HBsAg')], max_length=50),
        ),
        migrations.DeleteModel(
            name='LabResult',
        ),
    ]
