# Generated by Django 5.0.7 on 2024-08-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('LabManager', 'Lab Manager')], default='LabManager', max_length=50),
        ),
    ]
