# Generated by Django 5.0.7 on 2024-08-24 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Running Out', 'Running Out'), ('Out of Stock', 'Out of Stock')], default='Available', max_length=20)),
                ('stocked_date', models.DateField()),
                ('last_updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
