# Generated by Django 5.0.7 on 2024-08-24 23:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('chemicals', 'Chemicals'), ('equipment', 'Equipment'), ('consumables', 'Consumables')], max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('supplier', models.CharField(max_length=100)),
                ('stocking_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.commodity')),
            ],
        ),
    ]
